# Generated by Django 5.0.7 on 2025-10-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="platformuser",
            index=models.Index(fields=["email"], name="account_pla_email_d251f4_idx"),
        ),
        migrations.AddIndex(
            model_name="platformuser",
            index=models.Index(
                fields=["external_id"], name="account_pla_externa_3118ee_idx"
            ),
        ),
    ]
