# Generated by Django 5.0.7 on 2026-02-07 08:59

import common.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0004_team_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=common.uuid.unique_uuid4, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "fact_type",
                    models.PositiveIntegerField(
                        choices=[(1, "TEXT"), (2, "IMAGE"), (3, "GEO")]
                    ),
                ),
                ("info", models.JSONField(blank=True, default=dict)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="game.game",
                    ),
                ),
                (
                    "target_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="game.team",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fact_type"], name="fact_fact_fact_ty_15ad8e_idx"
                    ),
                    models.Index(fields=["game"], name="fact_fact_game_id_27a4d4_idx"),
                    models.Index(
                        fields=["target_team"], name="fact_fact_target__74b0d9_idx"
                    ),
                    models.Index(
                        fields=["game", "target_team"],
                        name="fact_fact_game_id_53abb9_idx",
                    ),
                ],
            },
        ),
    ]
