# Generated by Django 5.0.7 on 2026-09-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fact",
            name="fact_type",
            field=models.PositiveIntegerField(
                choices=[(1, "TEXT"), (2, "MEDIA"), (3, "GEO")]
            ),
        ),
    ]
