# Generated by Django 5.0.7 on 2025-12-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioncategory",
            name="priority",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
