# Generated by Django 5.0.7 on 2026-01-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_team_external_id"),
        ("qna", "0002_questioncategory_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="game.game",
                    ),
                ),
                (
                    "question_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_questions",
                        to="qna.questiontemplate",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["game"], name="qna_gameque_game_id_8d2914_idx")
                ],
                "unique_together": {("question_template", "game")},
            },
        ),
    ]
