# Generated by Django 5.0.7 on 2026-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0004_askedquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="askedquestion",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="askedquestion",
            name="answered",
            field=models.BooleanField(default=False),
        ),
    ]
