# Generated by Django 5.0.7 on 2026-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0005_askedquestion_accepted_askedquestion_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontemplate",
            name="info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
