# Generated by Django 5.0.7 on 2026-02-28 12:56

import common.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0006_questiontemplate_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontemplate",
            name="answer_instruction_type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "DRAW_CIRCLE_POINT_RADIUS"),
                    (2, "DRAW_CIRCLE_2_POINTS"),
                    (3, "SPLIT_BY_DIRECTION"),
                    (4, "HOTTER_COLDER"),
                    (5, "AREAS"),
                    (6, "CLOSER_TO_LINE"),
                    (7, "POLYGON_LOCATION"),
                    (99, "NO_INSTRUCTION"),
                ],
                default=common.constants.AnswerInstructionType["NO_INSTRUCTION"],
            ),
        ),
    ]
