# Generated by Django 5.0.7 on 2026-08-30 05:36

import common.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_player', '0001_initial'),
        ('qna', '0007_questiontemplate_answer_instruction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=common.uuid.unique_uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_key', models.CharField(max_length=512)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.PositiveIntegerField(choices=[(1, 'PENDING'), (2, 'UPLOADED'), (3, 'FAILED')], default=1)),
                ('asked_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='qna.askedquestion')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='profile_player.playerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['asked_question'], name='qna_attachm_asked_q_d18b00_idx'), models.Index(fields=['status'], name='qna_attachm_status_14f922_idx')],
            },
        ),
    ]
