# Generated by Django 5.0.7 on 2026-08-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0007_questiontemplate_answer_instruction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questiontemplate",
            name="answer_instruction_type",
        ),
        migrations.AddField(
            model_name="placeholderallowedvalue",
            name="info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
