# Generated by Django 5.0.7 on 2026-08-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0008_remove_questiontemplate_answer_instruction_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placeholderallowedvalue",
            name="placeholder",
        ),
        migrations.DeleteModel(
            name="Placeholder",
        ),
        migrations.DeleteModel(
            name="PlaceholderAllowedValue",
        ),
    ]
