# Generated by Django 5.0.7 on 2026-05-23 07:26

import common.uuid
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profile_player", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "location_pnt",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("accuracy", models.FloatField(blank=True, null=True)),
                (
                    "client",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "WEB_APP"),
                            (2, "ANDROID"),
                            (3, "IOS"),
                            (4, "TRACCAR"),
                        ]
                    ),
                ),
                ("info", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_player.playerprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player", "-created"],
                        name="live_locati_player__a9b551_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationSharingSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=common.uuid.unique_uuid4, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_sharing_enabled", models.BooleanField(default=False)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_sharing_setting",
                        to="profile_player.playerprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player"], name="live_locati_player__9dbff2_idx"
                    )
                ],
            },
        ),
    ]
