services:
  q_yaar_core:
    restart: always
    build:
      context: ./../q_yaar_platform
      dockerfile: ./../q_yaar_platform/Dockerfile-staging
    extra_hosts:
      # For ubuntu docker to access host machine services
      - "host.docker.internal:host-gateway"
    env_file: ./../build_meta/.env_staging
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
      - redis
    command: >
      bash -c "python manage.py migrate && gunicorn q_yaar.wsgi:application --bind 0.0.0.0:8000 --workers 5"

  # fast_worker:
  #   build:
  #     context: ./../q_yaar_platform
  #     dockerfile: ./../q_yaar_platform/Dockerfile-staging
  #   command: celery -A q_yaar worker -E -l info --concurrency=8 --pool=prefork -n fast_worker@qyaar.com  -Q example
  #   env_file: ./../build_meta/.env_staging
  #   networks:
  #     - backend

  # slow_worker:
  #   build:
  #     context: ./../q_yaar_platform
  #     dockerfile: ./../q_yaar_platform/Dockerfile-staging
  #   command: celery -A q_yaar worker -E -l info --concurrency=8 --pool=prefork -n slow_worker@qyaar.com  -Q default
  #   env_file: ./../build_meta/.env_staging
  #   networks:
  #     - backend

  # celery_beat:
  #   build:
  #     context: ./../q_yaar_platform
  #     dockerfile: ./../q_yaar_platform/Dockerfile-staging
  #   extra_hosts:
  #     # For ubuntu docker to access host machine services
  #     - "host.docker.internal:host-gateway"
  #   command: celery -A q_yaar beat -l debug
  #   env_file: ./../build_meta/.env_staging
  #   networks:
  #     - backend

  db:
    image: postgres
    restart: always
    env_file: ./../build_meta/.env_staging
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres:/var/lib/postgresql
    networks:
      - backend

  redis:
    image: redis:7.4-alpine
    restart: always
    volumes:
      - redis:/data
    command: >
      redis-server --save 20 1 --loglevel warning
    networks:
      - backend

networks:
  backend:


volumes:
  redis:
  postgres:
