# Generated by Django 5.0.7 on 2025-10-12 12:35

import common.uuid
import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pghistory", "0006_delete_aggregateevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("external_id", models.UUIDField(default=common.uuid.unique_uuid4)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "reward",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=common.uuid.unique_uuid4, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "reward",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["title"], name="card_deck_c_title_9e60e3_idx"),
                    models.Index(fields=["tags"], name="card_deck_c_tags_f696df_idx"),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="card",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "card_deck_cardevent" ("created", "description", "external_id", "id", "image", "is_deleted", "metadata", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reward", "tags", "title", "version") VALUES (NEW."created", NEW."description", NEW."external_id", NEW."id", NEW."image", NEW."is_deleted", NEW."metadata", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reward", NEW."tags", NEW."title", NEW."version"); RETURN NULL;',
                    hash="af17c3d6a459f54d941568c4528de972f251c007",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_9c36c",
                    table="card_deck_card",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="card",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "card_deck_cardevent" ("created", "description", "external_id", "id", "image", "is_deleted", "metadata", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reward", "tags", "title", "version") VALUES (NEW."created", NEW."description", NEW."external_id", NEW."id", NEW."image", NEW."is_deleted", NEW."metadata", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reward", NEW."tags", NEW."title", NEW."version"); RETURN NULL;',
                    hash="ec1c4f06479dfc624083b7ad4ab23a5f2f51e47b",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_fa0f5",
                    table="card_deck_card",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="cardevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="cardevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="card_deck.card",
            ),
        ),
    ]
