# Generated by Django 5.0.7 on 2025-10-19 05:04

import common.uuid
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pghistory", "0006_delete_aggregateevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=common.uuid.unique_uuid4, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "reward",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="CardEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("external_id", models.UUIDField(default=common.uuid.unique_uuid4)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "reward",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="card_deck.card",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CardTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="card_deck_c_name_311272_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="cards", to="card_deck.cardtag"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["title"], name="card_deck_c_title_9e60e3_idx"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="card",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "card_deck_cardevent" ("created", "description", "external_id", "id", "image", "is_deleted", "metadata", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reward", "title", "version") VALUES (NEW."created", NEW."description", NEW."external_id", NEW."id", NEW."image", NEW."is_deleted", NEW."metadata", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reward", NEW."title", NEW."version"); RETURN NULL;',
                    hash="8b269e92e3ef616258e731127a18a14f498b9895",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_9c36c",
                    table="card_deck_card",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="card",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "card_deck_cardevent" ("created", "description", "external_id", "id", "image", "is_deleted", "metadata", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reward", "title", "version") VALUES (NEW."created", NEW."description", NEW."external_id", NEW."id", NEW."image", NEW."is_deleted", NEW."metadata", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reward", NEW."title", NEW."version"); RETURN NULL;',
                    hash="b0b06b0da96f35d44da83a4d0ca071619d77d2cf",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_fa0f5",
                    table="card_deck_card",
                    when="AFTER",
                ),
            ),
        ),
    ]
