# Generated by Django 5.0.7 on 2025-10-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_deck", "0001_initial"),
        ("game", "0004_team_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "pile",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "DECK"), (2, "HAND"), (3, "DISCARD")], default=1
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="card_deck.card",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="game.team",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team", "pile"], name="card_deck_c_team_id_ea1e52_idx"
                    )
                ],
            },
        ),
    ]
