# Generated by Django 5.0.7 on 2025-10-12 12:06

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_deck", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="card",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="card",
            name="update_update",
        ),
        migrations.AddField(
            model_name="card",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cardevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="card",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "card_deck_cardevent" ("created", "description", "external_id", "id", "image", "is_deleted", "metadata", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reward", "tags", "title", "version") VALUES (NEW."created", NEW."description", NEW."external_id", NEW."id", NEW."image", NEW."is_deleted", NEW."metadata", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reward", NEW."tags", NEW."title", NEW."version"); RETURN NULL;',
                    hash="af17c3d6a459f54d941568c4528de972f251c007",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_9c36c",
                    table="card_deck_card",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="card",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "card_deck_cardevent" ("created", "description", "external_id", "id", "image", "is_deleted", "metadata", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reward", "tags", "title", "version") VALUES (NEW."created", NEW."description", NEW."external_id", NEW."id", NEW."image", NEW."is_deleted", NEW."metadata", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reward", NEW."tags", NEW."title", NEW."version"); RETURN NULL;',
                    hash="ec1c4f06479dfc624083b7ad4ab23a5f2f51e47b",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_fa0f5",
                    table="card_deck_card",
                    when="AFTER",
                ),
            ),
        ),
    ]
