# Generated by Django 5.0.7 on 2025-10-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "card_deck",
            "0002_remove_card_insert_insert_remove_card_update_update_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cardevent",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
