# Generated by Django 5.0.7 on 2025-12-20 06:37

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_deck", "0002_cardinstance"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="card",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="card",
            name="update_update",
        ),
        migrations.AddField(
            model_name="card",
            name="card_type",
            field=models.PositiveIntegerField(
                choices=[(1, "CURSE"), (2, "POWERUP")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cardevent",
            name="card_type",
            field=models.PositiveIntegerField(
                choices=[(1, "CURSE"), (2, "POWERUP")], default=1
            ),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="card",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "card_deck_cardevent" ("card_type", "created", "description", "external_id", "id", "image", "is_deleted", "metadata", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reward", "title", "version") VALUES (NEW."card_type", NEW."created", NEW."description", NEW."external_id", NEW."id", NEW."image", NEW."is_deleted", NEW."metadata", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reward", NEW."title", NEW."version"); RETURN NULL;',
                    hash="8e72b94f5c2cc9b690f836acceb144f3ef9c7598",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_9c36c",
                    table="card_deck_card",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="card",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "card_deck_cardevent" ("card_type", "created", "description", "external_id", "id", "image", "is_deleted", "metadata", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reward", "title", "version") VALUES (NEW."card_type", NEW."created", NEW."description", NEW."external_id", NEW."id", NEW."image", NEW."is_deleted", NEW."metadata", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reward", NEW."title", NEW."version"); RETURN NULL;',
                    hash="9e6f7cc228a6a135924cffd852b125247bf950d8",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_fa0f5",
                    table="card_deck_card",
                    when="AFTER",
                ),
            ),
        ),
    ]
