# Generated by Django 5.0.7 on 2026-02-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "card_deck",
            "0003_remove_card_insert_insert_remove_card_update_update_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_type",
            field=models.PositiveIntegerField(
                choices=[(1, "CURSE"), (2, "POWERUP"), (3, "TIME_BONUS")]
            ),
        ),
        migrations.AlterField(
            model_name="cardevent",
            name="card_type",
            field=models.PositiveIntegerField(
                choices=[(1, "CURSE"), (2, "POWERUP"), (3, "TIME_BONUS")]
            ),
        ),
    ]
