# Generated by Django 5.0.7 on 2026-08-10 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pushnotificationhistory",
            index=models.Index(
                fields=["user", "-created"], name="notificatio_user_id_ddb22d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotificationhistory",
            index=models.Index(
                fields=["user", "is_read", "-created"],
                name="notificatio_user_id_9a9853_idx",
            ),
        ),
    ]
