# Generated by Django 5.0.7 on 2025-10-18 07:11

import common.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profile_game_master", "0001_initial"),
        ("profile_player", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=common.uuid.unique_uuid4, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("game_code", models.CharField(max_length=8, unique=True)),
                (
                    "game_type",
                    models.PositiveIntegerField(choices=[(1, "HIDE_N_SEEK")]),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "game_status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "PENDING"), (2, "IN_PROGRESS"), (3, "COMPLETED")],
                        default=1,
                    ),
                ),
                ("info", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profile_game_master.gamemasterprofile",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        related_name="games",
                        to="profile_player.playerprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="game_game_name_ef2ba8_idx"),
                    models.Index(
                        fields=["game_code"], name="game_game_game_co_087e4c_idx"
                    ),
                    models.Index(
                        fields=["game_code", "game_status"],
                        name="game_game_game_co_f35a39_idx",
                    ),
                ],
            },
        ),
    ]
