# Generated by Django 5.0.7 on 2025-10-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="players",
        ),
    ]
