# Generated by Django 5.0.7 on 2025-10-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_game_players"),
        ("profile_player", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("team_name", models.CharField(max_length=100)),
                ("team_colour", models.CharField(max_length=50)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamPlayerRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_player.playerprofile",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.team"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["team_name"], name="game_team_team_na_96604e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["game", "team_name"], name="game_team_game_id_5308c6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("game", "team_name")},
        ),
        migrations.AddIndex(
            model_name="teamplayerrelation",
            index=models.Index(fields=["team"], name="game_teampl_team_id_0794e0_idx"),
        ),
        migrations.AddIndex(
            model_name="teamplayerrelation",
            index=models.Index(fields=["game"], name="game_teampl_game_id_3d09f6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teamplayerrelation",
            unique_together={("player", "game")},
        ),
    ]
