# Generated by Django 5.0.7 on 2025-10-20 10:27

import common.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_team_teamplayerrelation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="external_id",
            field=models.UUIDField(default=common.uuid.unique_uuid4, unique=True),
        ),
    ]
