# Generated by Django 5.0.7 on 2026-06-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_team_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_visibility_mode",
            field=models.PositiveIntegerField(
                choices=[(1, "PUBLIC"), (2, "PRIVATE")], default=1
            ),
        ),
    ]
