# Generated by Django 5.0.7 on 2026-06-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_game_game_visibility_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_visibility_mode",
            field=models.PositiveIntegerField(
                choices=[(1, "PUBLIC"), (2, "PRIVATE")], default=2
            ),
        ),
    ]
