# Generated by Django 5.0.7 on 2026-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_game_game_visibility_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_type",
            field=models.PositiveIntegerField(
                choices=[(1, "PLAYER"), (2, "SPECTATOR")], default=1
            ),
        ),
    ]
