# Generated by Django 5.0.7 on 2026-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_team_team_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("team_type", 2)),
                fields=("game",),
                name="unique_spectator_team_per_game",
            ),
        ),
    ]
