# Generated by Django 5.0.7 on 2026-02-28 15:18

import common.uuid
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0004_team_external_id'),
        ('pghistory', '0006_delete_aggregateevent'),
        ('profile_player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=common.uuid.unique_uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('reported_time', models.DateTimeField()),
                ('client', models.PositiveIntegerField(choices=[(1, 'OWNTRACS'), (2, 'QYAAR')])),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='profile_player.playerprofile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='game.team')),
            ],
        ),
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('external_id', models.UUIDField(default=common.uuid.unique_uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('reported_time', models.DateTimeField()),
                ('client', models.PositiveIntegerField(choices=[(1, 'OWNTRACS'), (2, 'QYAAR')])),
                ('game', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='game.game')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='location.location')),
                ('player', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='profile_player.playerprofile')),
                ('team', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='game.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationSharingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_sharing_enabled', models.BooleanField(default=False)),
                ('tracking_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_sharing_setting', to='profile_player.playerprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['player'], name='location_lo_player__651fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['game'], name='location_lo_game_id_ba4d89_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['team'], name='location_lo_team_id_5c0ea5_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='location',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "location_locationevent" ("accuracy", "client", "created", "external_id", "game_id", "id", "lat", "lon", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "player_id", "reported_time", "team_id") VALUES (NEW."accuracy", NEW."client", NEW."created", NEW."external_id", NEW."game_id", NEW."id", NEW."lat", NEW."lon", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."player_id", NEW."reported_time", NEW."team_id"); RETURN NULL;', hash='820175a201ac3d5578ad58158d09ea7ba537be37', operation='INSERT', pgid='pgtrigger_insert_insert_98cd4', table='location_location', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='location',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "location_locationevent" ("accuracy", "client", "created", "external_id", "game_id", "id", "lat", "lon", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "player_id", "reported_time", "team_id") VALUES (NEW."accuracy", NEW."client", NEW."created", NEW."external_id", NEW."game_id", NEW."id", NEW."lat", NEW."lon", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."player_id", NEW."reported_time", NEW."team_id"); RETURN NULL;', hash='1a3d264f4656c3e2c22d2bf9c7c1e4aefefe4d6e', operation='UPDATE', pgid='pgtrigger_update_update_471d2', table='location_location', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='locationsharingsetting',
            index=models.Index(fields=['tracking_code'], name='location_lo_trackin_03715d_idx'),
        ),
    ]
