# Generated by Django 5.0.7 on 2026-03-02 13:18

import common.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0004_team_external_id"),
        ("profile_player", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=common.uuid.unique_uuid4, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "client",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "WEB_APP"),
                            (2, "ANDROID"),
                            (3, "IOS"),
                            (4, "EXTERNAL_TRACCAR"),
                        ]
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="profile_player.playerprofile",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="game.team",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player"], name="location_lo_player__651fc1_idx"
                    ),
                    models.Index(
                        fields=["game"], name="location_lo_game_id_ba4d89_idx"
                    ),
                    models.Index(
                        fields=["team"], name="location_lo_team_id_5c0ea5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationSharingSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_sharing_enabled", models.BooleanField(default=False)),
                (
                    "tracking_code",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_sharing_setting",
                        to="profile_player.playerprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tracking_code"], name="location_lo_trackin_03715d_idx"
                    )
                ],
            },
        ),
    ]
