# Generated by Django 5.0.7 on 2026-03-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name="location",
            name="lon",
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
