# Generated by Django 5.0.7 on 2026-02-28 17:12

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='location',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='location',
            name='update_update',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='reported_time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='locationevent',
            old_name='reported_time',
            new_name='timestamp',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='location',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "location_locationevent" ("accuracy", "client", "created", "external_id", "game_id", "id", "lat", "lon", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "player_id", "team_id", "timestamp") VALUES (NEW."accuracy", NEW."client", NEW."created", NEW."external_id", NEW."game_id", NEW."id", NEW."lat", NEW."lon", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."player_id", NEW."team_id", NEW."timestamp"); RETURN NULL;', hash='130195f1a6cc9da0156a5be9aef3ae6d299cb27c', operation='INSERT', pgid='pgtrigger_insert_insert_98cd4', table='location_location', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='location',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "location_locationevent" ("accuracy", "client", "created", "external_id", "game_id", "id", "lat", "lon", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "player_id", "team_id", "timestamp") VALUES (NEW."accuracy", NEW."client", NEW."created", NEW."external_id", NEW."game_id", NEW."id", NEW."lat", NEW."lon", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."player_id", NEW."team_id", NEW."timestamp"); RETURN NULL;', hash='715a5b002badad66567b52e53d1d59dbe946d82a', operation='UPDATE', pgid='pgtrigger_update_update_471d2', table='location_location', when='AFTER')),
        ),
    ]
