# Generated by Django 5.0.7 on 2026-02-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='client',
            field=models.PositiveIntegerField(choices=[(1, 'WEB_APP'), (2, 'ANDROID'), (3, 'IOS'), (4, 'EXTERNAL_TRACCAR')]),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='client',
            field=models.PositiveIntegerField(choices=[(1, 'WEB_APP'), (2, 'ANDROID'), (3, 'IOS'), (4, 'EXTERNAL_TRACCAR')]),
        ),
    ]
